name: Cypress CI for React

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Install serve
        run: npm install -g serve

      - name: Start server and run Cypress
        run: |
          serve -s build -l 5000 &
          npx cypress run --headless --config baseUrl=http://localhost:5000
